### ISSUE TITLE
Multi-Core link

### ISSUE THREAD

**Issue by dilwar-crnlab** [Mininet-Optical/mininet-optical#130]
Does the link.py support multi core link?

**Comment by lantz** [comment]
Please do not abuse the issues system with random questions. :(

**Comment by dilwar-crnlab** [comment]
Have you understood my question?

**Comment by lantz** [comment]
Do you understand that github issues are a bug reporting system, not a technical support forum?

**Comment by DilwarS** [comment]
Thank you
