### ISSUE TITLE
Cross-validation tests broken and not being run

### ISSUE THREAD

**Issue by lantz** [Mininet-Optical/mininet-optical#134]
### Expected/Desired Behavior:
Cross-validation tests should run and pass as part of github actions workflow
### Actual Behavior:
Cross-validation tests are not being run as part of the CI workflow
### Detailed Steps to Reproduce the Behavior:
Look at Actions> observe that the cross-validation tests are not being run.

**Comment by juraul1** [comment]
Can we close that now?

**Comment by lantz** [comment]
@juraul1  yes; should have added `closes #134` in the commits for #127.

Fixed in #127
